lobby and match making server now our own + baby carrot state machine
studiosstudios/rooted pull request #21
Opened 2024-03-25 06:25 UTC by joshuakguo

- Moving over to our own lobby and match making server
- Baby carrot AI is now a state machine
- Previous behavior is a ROAM state and there is a new HOLD state
- non hosts now no longer initialize their AI Controller

it created this Android.mk file, idk what it does, hopefully nothing

2024-03-25 18:24 UTC, jffzhou commented on source/controllers/AIController.cpp
> +                babyCarrot->setState(State::HOLD);
this line seems redundant

2024-03-25 18:28 UTC, jffzhou requested changes
it seems like since ```updateBabyCarrotState``` is called every time ```updateBabyCarrot``` is called that the states would be changing really rapidly, could you make it only called once every second (or something like that) instead?

also make sure to remove the build folder before merging

2024-03-26 23:13 UTC, joshuakguo commented
removed build folder and changed state update to only when there's no target

2024-03-26 23:14 UTC, joshuakguo reviewed
changes made

2024-03-26 23:15 UTC, joshuakguo reviewed
im stupid

2024-03-27 16:59 UTC, merged